# Tasks ########################################################################

# Test =========================================================================

# test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.test]
run = "cargo nextest run"


# test:watch ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."test:watch"]
run = "bacon nextest"

# Publish ======================================================================

# publish ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.publish]
run = "fnox exec -- cargo publish --allow-dirty"

# Examples =====================================================================

# example ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.example]
usage = '''
arg "<example>" help="Example name"
'''
run = "cargo run --bin esc -- build --project ./examples/{{usage.example}}/"
