# Tasks ########################################################################

# Publish ======================================================================

# publish ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.publish]
run = "fnox exec -- cargo publish --allow-dirty"
