# Monorepo =====================================================================

monorepo_root = true
[monorepo]
config_roots = ["pkgs/*"]

[tools]

# Stack ========================================================================

# Node.js
node = "24"
"npm:pnpm" = { version = "next-12", allow_builds = true }

# Tools
cargo-binstall = "latest" # Install cargo binaries

# Settings =====================================================================

[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml


# Tasks ========================================================================

[tasks.install]
depends = ["install/pnpm"]

[tasks."install/pnpm"]
run = "pnpm install"
