packages:
  - "pkgs/*"
  - "pkgs/*/examples/*"

minimumReleaseAgeExclude:
  - "@js-fns/dev@0.3.4 || 0.3.5"
  - "@typescript/typescript-darwin-arm64@7.1.0-dev.20260913.1"
  - "@typescript/typescript-darwin-x64@7.1.0-dev.20260913.1"
  - "@typescript/typescript-linux-arm64@7.1.0-dev.20260913.1"
  - "@typescript/typescript-linux-arm@7.1.0-dev.20260913.1"
  - "@typescript/typescript-linux-x64@7.1.0-dev.20260913.1"
  - "@typescript/typescript-win32-arm64@7.1.0-dev.20260913.1"
  - "@typescript/typescript-win32-x64@7.1.0-dev.20260913.1"
  - typescript@7.1.0-dev.20260913.1

allowBuilds:
  esbuild: true
  workerd: true
  "@vscode/vsce-sign": false
  keytar: false
